language: python
cache:
  pip: true
  directories:
    - eggs
    - downloads
python:
  - 2.7
  - 3.6
  - 3.7
env:
  - PLONE_VERSION=5.1
  - PLONE_VERSION=5.2
jobs:
  exclude:
    - python: 3.6
      env: PLONE_VERSION=5.1
    - python: 3.7
      env: PLONE_VERSION=5.1
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements-$PLONE_VERSION.txt
  - sed -ie "s#plone-5.1.x.cfg#plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - bin/buildout -c travis.cfg -n buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
