language: python
sudo: true
cache:
  pip: true
  directories:
    - eggs
    - downloads
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
install:
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
  - sed -ie "s#plone-5.1.x.cfg#plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - bin/buildout -Nc travis.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test --all
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
