name: tests

on:
  push:
    branches-ignore:
      - "releases/**"
      - "master"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - ["Py2.7-Plone5.2", "2.7", "5.2", "ubuntu-20.04"]
          - ["Py3.6-Plone5.2", "3.6", "5.2", "ubuntu-20.04"]
          - ["Py3.7-Plone5.2", "3.7", "5.2", "ubuntu-latest"]
          - ["Py3.8-Plone5.2", "3.8", "5.2", "ubuntu-latest"]
          - ["Py3.8-Plone6.0", "3.8", "6.0", "ubuntu-latest"]
          - ["Py3.9-Plone6.0", "3.9", "6.0", "ubuntu-latest"]
          - ["Py3.10-Plone6.0", "3.10", "6.0", "ubuntu-latest"]
          - ["Py3.11-Plone6.0", "3.11", "6.0", "ubuntu-latest"]
    runs-on: ${{ matrix.config[3] }}
    name: ${{ matrix.config[0] }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config[1] }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            **/eggs
            **/downloads
          key: ${{ runner.os }}-cache-${{ hashFiles('setup.*', '*.cfg') }}-${{ matrix.config[0] }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv -p `which python` .
          bin/pip install -r requirements-${{ matrix.config[2] }}.txt
          sed -ie "s#plone-5.2.x.cfg#plone-${{ matrix.config[2] }}.x.cfg#" buildout.cfg
          bin/buildout
      - name: Test
        run: |
          bin/code-analysis
          PYTHONWARNINGS=ignore bin/test --all
          bin/createcoverage
          bin/coverage report --fail-under=85
